deployments:
  deploymentGating:
    enabled: true
    retry: 1000
    sleep: 10
    environments: 
    - Development
    - Production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzIwM2VkMWE0LTE0MmEtNDE0Yy1hYjY4LTA1OGMzMDBkODAxMS8zY2M3Njc1OC1iYzFjLTExZWUtYjY3ZC0wYWJlM2Y0YTY2MDE=
