# This is a basic workflow to help you get started with Actions

name: My Deployment flow

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  deploy-to-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    name: Deploy to Dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create dev deployment
        id: deployment_dev
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: ::::development-ã‚¹
      - name: Running dev deployment
        run: |
          echo Deploying to staging...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update dev deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment_dev.outputs.deployment_id }}
          
# This workflow contains a single job called "build"
  deploy-to-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    name: Deploy to Testing
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create test deployment
        id: deployment_test
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: 111:test_staging-env
      - name: Running test deployment
        run: |
          echo Deploying to staging...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update test deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment_test.outputs.deployment_id }}
          
  # This workflow contains a single job called "build"
  deploy-to-staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    name: Deploy to Staging
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create staging deployment
        id: deployment_staging
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: some-staging-env
      - name: Running staging deployment
        run: |
          echo Deploying to staging...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update staging deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment_staging.outputs.deployment_id }}
  deploy-to-prod:
    runs-on: ubuntu-18.04
    name: Deploy to Production
    if: ${{ github.ref == 'refs/heads/master' }}
    steps: 
      - uses: chrnorm/deployment-action@releases/v1
        name: Create prod deployment
        id: deployment_prod
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: 1111:prod_env
      - name: Running production deployment
        run: |
          echo Deploying to production...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update prod deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment_prod.outputs.deployment_id }}
  deploy-to-prod-normal:
    runs-on: ubuntu-18.04
    name: Deploy to Normal Production
    if: ${{ github.ref == 'refs/heads/master' }}
    steps: 
      - uses: chrnorm/deployment-action@releases/v1
        name: Create prod deployment
        id: deployment_prod
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: prod-normal
      - name: Running production deployment
        run: |
          echo Deploying to production...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update prod deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment_prod.outputs.deployment_id }}
